"use client"
import { Geist, Geist_Mono } from "next/font/google";
import { useEffect } from "react";
import 'swiper/css'; // Core Swiper styles
import 'swiper/css/navigation'; // For navigation arrows
import 'swiper/css/pagination'; // For pagination dots
import 'bootstrap/dist/css/bootstrap.min.css'; // Import Bootstrap CSS
import "./globals.css";
import "./page.module.css";
import 'bootstrap/dist/js/bootstrap.bundle.min.js'; // Import Bootstrap JavaScript
import Footer from "./_Components/Footer/Footer";
import Navbar from "./_Components/Navbar/Navbar";
  
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
